### ISSUE TITLE
PostgreSQL Compatibility; Installation Fails

### ISSUE THREAD

**Issue by haslo** [verbb/zen#1]
### Describe the bug

The plugin always assumes that the backend is MySQL, and thus does not install on PostgreSQL backends.

### Steps to reproduce

1. Install CraftCMS with a PostgreSQL backend
2. Try to install the Zen plugin
3. Observe error message "type 'longblob' does not exist", which stems from https://github.com/verbb/zen/blob/7ad1e8d5a60b9f93a3f2a2f996ee97c4999b5393/src/migrations/Install.php#L40

### Craft CMS version

4.5.9

### Plugin version

1.0.0

### Multi-site?

No

### Additional context

This is on a fresh install. The plugin obviously works fine with MySQL, but PostgreSQL doesn't have the "longblob" type.

**Comment by engram-design** [comment]
Ah, my mistake - I actually thought `longblob` was available on both. Fixed in [1.0.1](https://github.com/verbb/zen/releases/tag/1.0.1)
