### ISSUE TITLE
Provide a "no backup" option

### ISSUE THREAD

**Issue by mandrasch** [verbb/zen#16]
### What are you trying to do?

On some servers, there is no allowed access to `mysqldump` - therefore import fails with 
`craft\errors\ShellCommandException | The shell command "mysqldump ...`. 

### What's your proposed solution?

Provide a "no backup" option like FeedMe.

### Additional context

Thanks very much, awesome plugin! 👍

**Comment by engram-design** [comment]
Added for the next release. To get this early, run `composer require verbb/zen:"dev-craft-4 as 1.0.4"` or  `composer require verbb/zen:"dev-craft-5 as 2.0.0"`.

**Comment by engram-design** [comment]
Added in [2.0.1](https://github.com/verbb/zen/releases/tag/2.0.1)
