### ISSUE TITLE
Support for Verbb Events

### ISSUE THREAD

**Issue by CharlieGentle** [verbb/zen#2]
### What are you trying to do?

I was hoping to able to use Zen to export/import Events (and Tickets) from your Events plugin. Purchased tickets wouldn't be required.

### What's your proposed solution?

Ideally, events would show up in the Elements list and be able to be exported/imported like everything else.

**Comment by engram-design** [comment]
Added for the next release. You'll need to get on dev versions of both plugins:

`composer require verbb/zen:"dev-craft-4 as 1.0.1"`
`composer require verbb/events:"dev-craft-4 as 2.0.2"`

**Comment by CharlieGentle** [comment]
Brilliant, thanks
