### ISSUE TITLE
Date issues

### ISSUE THREAD

**Issue by jaydensmith** [verbb/zen#3]
### Describe the bug

Hey @engram-design, I'm trying out this plugin, looks great!

I have some issues selecting a date, seems like when I choose a date where the day component is > 12, I get NaN/NaN/NaN batman. If the day is 12 or less it works fine, but the formatting is wrong for the locale, I'm not sure if it's loading the correct date in that case.

<img width="562" alt="Screenshot 2023-12-06 at 6 25 06 pm" src="https://github.com/verbb/zen/assets/16344913/0979a950-78dc-4aa9-84ca-c002d5d82e05">
<img width="549" alt="Screenshot 2023-12-06 at 6 24 59 pm" src="https://github.com/verbb/zen/assets/16344913/c78dab65-23b7-4b97-92e4-59d6fd6ab4fc">

### Steps to reproduce

1. Set formatting locale to English (Australia)
2. Choose a day > 12 in Zen.

### Craft CMS version

4.5.11.1

### Plugin version

1.0.1

### Multi-site?

No

**Comment by engram-design** [comment]
Not sure how I missed that, thanks Jayden! 

Fixed for the next release. To get this early, run `composer require verbb/zen:"dev-craft-4 as 1.0.1"`

**Comment by engram-design** [comment]
Fixed in [1.0.2](https://github.com/verbb/zen/releases/tag/1.0.2)
