### ISSUE TITLE
Excluding of elements not possible in German locale

### ISSUE THREAD

**Issue by gglnx** [verbb/zen#6]
### Describe the bug

It's the Umlauts again. Zen uses the translated labels as IDs / form names, which gets encoded to a JSON and JSON decoding fails on the backend.

<img width="407" alt="SCR-20240305-rufp" src="https://github.com/verbb/zen/assets/23519/b84e41d2-cbf8-4a39-8484-9cafdc32db5f">

The exception:

> Malformed UTF-8 characters, possibly incorrectly encoded
> /vendor/yiisoft/yii2/helpers/BaseJson.php:147
> /vendor/yiisoft/yii2/helpers/BaseJson.php:128

### Steps to reproduce

1. Switch to German
2. Start an import
3. Exclude one element from »Einträge« (entries)
4. Start the import

### Craft CMS version

4.8.0

### Plugin version

1.0.3

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/zen:"dev-craft-4 as 1.0.3"`.

**Comment by gglnx** [comment]
Works, thank you!
