### ISSUE TITLE
Navigation node preview are rendered with overlaying buttons

### ISSUE THREAD

**Issue by gglnx** [verbb/zen#8]
### Describe the bug

On the preview before importing, a Zen export containing navigation nodes, I get all nodes overlayed with their editing buttons:

<img width="471" alt="SCR-20240314-kyft" src="https://github.com/verbb/zen/assets/23519/61e4fc1c-a22e-4df5-ad13-75fea9181512">

I think that's because Zen requests `elementHtml` with the context `index` and `verbb/navigation` injects that (see https://github.com/verbb/navigation/blob/craft-4/src/elements/Node.php#L176)

### Steps to reproduce

1. Export navigation nodes
2. Import navigation nodes

### Craft CMS version

4.8.2

### Plugin version

1.0.3@dev

### Multi-site?

Yes

**Comment by engram-design** [comment]
Yep, that's _supposed to be handled, but likely a regression on my end - and it all changes again in Craft 5. More of a Navigation plugin issue though. To get this early, run `composer require verbb/navigation:"dev-craft-4 as 2.0.26"`.

**Comment by engram-design** [comment]
Fixed in [2.0.27](https://github.com/verbb/navigation/releases/tag/2.0.27)
